version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229" # Solo si necesitas depuración
    environment:
      - NODE_ENV=development
      - DEBUG=nest:*
    command: npm run start:dev